# Generated by Django 5.1.7 on 2025-12-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_eventparticipation'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipation',
            name='status',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
