# Generated by Django 5.1.7 on 2025-12-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_eventparticipation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipation',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
