# Generated by Django 5.1.7 on 2025-12-19 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0005_programme'),
        ('student', '0005_alter_eventparticipation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammeParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(blank=True, max_length=100)),
                ('song_name', models.CharField(max_length=200)),
                ('members_count', models.IntegerField()),
                ('status', models.CharField(default='requested', max_length=50)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_manager.programme')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
        migrations.DeleteModel(
            name='EventParticipation',
        ),
    ]
