# Generated by Django 5.1.7 on 2025-12-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_programmeparticipation_delete_eventparticipation'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.FileField(default='null', upload_to='proof'),
        ),
    ]
