# Generated by Django 5.1.7 on 2025-12-31 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_student_registration_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmeparticipation',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
