# Generated by Django 5.1.7 on 2025-12-16 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmanager',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='eventmanager',
            name='qualification',
        ),
    ]
