# Generated by Django 5.1.7 on 2025-12-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0002_remove_eventmanager_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmanager',
            name='semester',
            field=models.IntegerField(default=0),
        ),
    ]
