# Generated by Django 5.1.7 on 2025-12-19 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0004_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('programme_type', models.CharField(max_length=50)),
                ('min_members', models.IntegerField(default=1)),
                ('max_members', models.IntegerField()),
                ('allowed_song_type', models.CharField(max_length=200)),
                ('time_limit', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_manager.event')),
            ],
        ),
    ]
