# Generated by Django 5.1.7 on 2025-12-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0005_programme'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmanager',
            name='student_id',
            field=models.FileField(default='null', upload_to='proof'),
        ),
    ]
