# Generated by Django 5.1.7 on 2025-12-27 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0006_eventmanager_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmanager',
            name='registration_no',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
