# Generated by Django 5.1.7 on 2025-12-30 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0007_eventmanager_registration_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='poster',
            field=models.FileField(blank=True, null=True, upload_to='poster'),
        ),
    ]
