# Generated by Django 5.1.7 on 2026-02-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0009_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
